import { ProspectInput } from "./types";

/**
 * DATASET STAGE A: 20 CASOS PARA ROMPER REGLAS
 *
 * Objetivo: Encontrar edge cases y errores de reglas antes de testing masivo
 * Distribución: 5 bodegas + 5 restaurantes + 5 retail + 5 servicios
 */

// ============================================================================
// BODEGAS (5 casos)
// ============================================================================

export const BODEGA_PREMIUM: ProspectInput = {
  id: "bodega-premium-001",
  nombreEmpresa: "Bodega Premium",
  rubro: "Bodega de vinos premium con enoturismo",
  website: "bodegapremium.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: true,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: true,
    hasMetaPixel: true,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: true,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 200,
    imageCount: 30,
    mainNavSections: ["INICIO", "VINOS", "TOURS", "TIENDA", "CONTACTO"],
  },
};

export const BODEGA_EXPORTACION: ProspectInput = {
  id: "bodega-export-001",
  nombreEmpresa: "Bodega de Exportación",
  rubro: "Bodega de exportación B2B",
  website: "bodegaexport.com.ar",
  signals: null, // TESTING: Sin signals
};

export const BODEGA_BOUTIQUE: ProspectInput = {
  id: "bodega-boutique-001",
  nombreEmpresa: "Bodega Boutique",
  rubro: "Bodega familiar pequeña",
  website: "bodegaboutique.com.ar",
  signals: {
    accessible: true,
    httpsOk: false, // EDGE CASE: Sin HTTPS
    hasPhone: false,
    hasAddress: false,
    hasContactForm: false,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: true,
    socialLinksFound: ["facebook.com"],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: false,
    hasGA4: false,
    h1Count: 0,
    hasSchema: false,
    hasSitemap: false,
    hasCanonical: false,
    hasOgTags: false,
    hasMetaDescription: false,
    estimatedPageWeightKb: 5,
    imageCount: 1,
    mainNavSections: ["BODEGA"],
  },
};

export const BODEGA_VENTA_DIRECTA: ProspectInput = {
  id: "bodega-venta-001",
  nombreEmpresa: "Bodega Venta Directa",
  rubro: "Bodega con ventas en línea",
  website: "bodegaventa.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: false,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: false,
    socialLinksFound: [],
    hasEcommerce: true,
    hasMetaPixel: false, // EDGE CASE: Ecommerce sin Meta Pixel
    hasAnalytics: true,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: false,
    hasOgTags: false,
    hasMetaDescription: true,
    estimatedPageWeightKb: 80,
    imageCount: 15,
    mainNavSections: ["INICIO", "VINOS", "TIENDA", "CONTACTO"],
  },
};

export const BODEGA_RESTAURANTE: ProspectInput = {
  id: "bodega-rest-001",
  nombreEmpresa: "Bodega + Restaurante",
  rubro: "Bodega con restaurante incorporado",
  website: "bodegarestaurante.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: false,
    hasLeadForm: false,
    hasOnlineBooking: true,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com", "facebook.com"],
    hasEcommerce: true,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 150,
    imageCount: 20,
    mainNavSections: ["INICIO", "BODEGA", "RESTAURANTE", "RESERVAS", "TIENDA"],
  },
};

// ============================================================================
// RESTAURANTES (5 casos)
// ============================================================================

export const RESTAURANTE_FUSION: ProspectInput = {
  id: "rest-fusion-001",
  nombreEmpresa: "Restaurante Fusión",
  rubro: "Restaurante de comida fusión",
  website: "restaurantefusion.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: true,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: true,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 120,
    imageCount: 25,
    mainNavSections: ["INICIO", "MENU", "RESERVAR", "CONTACTO"],
  },
};

export const RESTAURANTE_CASUAL: ProspectInput = {
  id: "rest-casual-001",
  nombreEmpresa: "Restaurante Casual",
  rubro: "Restaurante casual sin pretensiones",
  website: "restaurantecasual.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: false,
    hasContactForm: false,
    hasLeadForm: false,
    hasOnlineBooking: false, // EDGE CASE: Reservas con WhatsApp, no detectable
    hasSocialLinks: true,
    socialLinksFound: ["whatsapp.com", "instagram.com"],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: false,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: false,
    hasCanonical: false,
    hasOgTags: false,
    hasMetaDescription: true,
    estimatedPageWeightKb: 40,
    imageCount: 8,
    mainNavSections: ["MENU", "CONTACTO"],
  },
};

export const RESTAURANTE_DELIVERY: ProspectInput = {
  id: "rest-delivery-001",
  nombreEmpresa: "Restaurante Delivery",
  rubro: "Restaurante solo delivery",
  website: "restaurantedelivery.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: false,
    hasContactForm: false,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: false,
    socialLinksFound: [],
    hasEcommerce: true,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: false,
    h1Count: 0,
    hasSchema: false,
    hasSitemap: false,
    hasCanonical: false,
    hasOgTags: false,
    hasMetaDescription: false,
    estimatedPageWeightKb: 60,
    imageCount: 10,
    mainNavSections: ["MENU", "PEDIR"],
  },
};

export const RESTAURANTE_FINE_DINING: ProspectInput = {
  id: "rest-fine-001",
  nombreEmpresa: "Fine Dining Restaurant",
  rubro: "Restaurante de alta cocina",
  website: "finedining.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: true,
    hasOnlineBooking: true,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: false,
    hasMetaPixel: true,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: true,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 180,
    imageCount: 40,
    mainNavSections: ["INICIO", "TASTING MENU", "RESERVAR", "GALERIA", "CONTACTO"],
  },
};

export const RESTAURANTE_POPUP: ProspectInput = {
  id: "rest-popup-001",
  nombreEmpresa: "Restaurante Popup",
  rubro: "Restaurante popup temporal",
  website: "restaurantepopup.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: false,
    hasAddress: false,
    hasContactForm: true,
    hasLeadForm: true,
    hasOnlineBooking: true,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: false,
    hasCanonical: false,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 50,
    imageCount: 12,
    mainNavSections: ["INICIO", "EVENTO", "RESERVAR"],
  },
};

// ============================================================================
// RETAIL (5 casos)
// ============================================================================

export const RETAIL_MODA: ProspectInput = {
  id: "retail-moda-001",
  nombreEmpresa: "Tienda de Moda",
  rubro: "Boutique de moda y diseño",
  website: "tiendamoda.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: true,
    hasMetaPixel: true,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: true,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 250,
    imageCount: 50,
    mainNavSections: ["INICIO", "CATALOGO", "TIENDA", "CONTACTO"],
  },
};

export const RETAIL_ELECTRODOMESTICOS: ProspectInput = {
  id: "retail-electro-001",
  nombreEmpresa: "Tienda Electrodomésticos",
  rubro: "Tienda de electrodomésticos",
  website: "tiendaelectro.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: false,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: false,
    socialLinksFound: [],
    hasEcommerce: true,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: false,
    hasMetaDescription: true,
    estimatedPageWeightKb: 300,
    imageCount: 80,
    mainNavSections: ["INICIO", "PRODUCTOS", "OFERTAS", "CONTACTO"],
  },
};

export const RETAIL_LIBROS: ProspectInput = {
  id: "retail-libros-001",
  nombreEmpresa: "Librería Online",
  rubro: "Tienda online de libros",
  website: "libreriaonline.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: false,
    hasAddress: false,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: true,
    socialLinksFound: ["facebook.com"],
    hasEcommerce: true,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: false,
    hasMetaDescription: true,
    estimatedPageWeightKb: 100,
    imageCount: 30,
    mainNavSections: ["CATALOGO", "COMPRAR", "CONTACTO"],
  },
};

export const RETAIL_ARTESANIA: ProspectInput = {
  id: "retail-artesania-001",
  nombreEmpresa: "Tienda Artesanía",
  rubro: "Tienda de artesanía local",
  website: "tiendaartesania.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com", "facebook.com"],
    hasEcommerce: true,
    hasMetaPixel: false,
    hasAnalytics: false,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: false,
    hasCanonical: false,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 70,
    imageCount: 20,
    mainNavSections: ["PRODUCTOS", "TIENDA", "CONTACTO"],
  },
};

export const RETAIL_PREMIUM: ProspectInput = {
  id: "retail-premium-001",
  nombreEmpresa: "Retail Premium",
  rubro: "Tienda premium de accesorios",
  website: "retailpremium.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: true,
    hasOnlineBooking: false,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: true,
    hasMetaPixel: true,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: true,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 200,
    imageCount: 35,
    mainNavSections: ["INICIO", "CATALOGO", "TIENDA", "BLOG", "CONTACTO"],
  },
};

// ============================================================================
// SERVICIOS (5 casos)
// ============================================================================

export const SERVICIO_CONSULTORIA: ProspectInput = {
  id: "svc-consultoria-001",
  nombreEmpresa: "Consultoría Empresarial",
  rubro: "Consultora de negocios",
  website: "consultoria.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: true,
    hasOnlineBooking: false,
    hasSocialLinks: true,
    socialLinksFound: ["linkedin.com"],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 80,
    imageCount: 15,
    mainNavSections: ["INICIO", "SERVICIOS", "PORTFOLIO", "CONTACTO"],
  },
};

export const SERVICIO_AGENCIA_MARKETING: ProspectInput = {
  id: "svc-marketing-001",
  nombreEmpresa: "Agencia de Marketing",
  rubro: "Agencia de marketing digital",
  website: "agenciamarketing.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: false,
    hasContactForm: true,
    hasLeadForm: true,
    hasOnlineBooking: true, // EDGE CASE: Agendar llamada
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com", "linkedin.com"],
    hasEcommerce: false,
    hasMetaPixel: true,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 120,
    imageCount: 20,
    mainNavSections: ["INICIO", "SERVICIOS", "CASOS", "BLOG", "AGENDAR"],
  },
};

export const SERVICIO_ABOGACIA: ProspectInput = {
  id: "svc-abog-001",
  nombreEmpresa: "Estudio Jurídico",
  rubro: "Estudio de abogados",
  website: "estudiojuridico.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: false,
    socialLinksFound: [],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: false,
    hasMetaDescription: true,
    estimatedPageWeightKb: 60,
    imageCount: 8,
    mainNavSections: ["INICIO", "PRACTICAS", "ABOGADOS", "CONTACTO"],
  },
};

export const SERVICIO_FITNESS: ProspectInput = {
  id: "svc-fitness-001",
  nombreEmpresa: "Gym Premium",
  rubro: "Gimnasio con clases personalizadas",
  website: "gyepremium.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: true,
    hasContactForm: true,
    hasLeadForm: true,
    hasOnlineBooking: true,
    hasSocialLinks: true,
    socialLinksFound: ["instagram.com"],
    hasEcommerce: true,
    hasMetaPixel: true,
    hasAnalytics: true,
    hasGA4: true,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: true,
    hasMetaDescription: true,
    estimatedPageWeightKb: 150,
    imageCount: 30,
    mainNavSections: ["INICIO", "CLASES", "PLANES", "AGENDAR", "CONTACTO"],
  },
};

export const SERVICIO_CONTABILIDAD: ProspectInput = {
  id: "svc-conta-001",
  nombreEmpresa: "Contador Público",
  rubro: "Estudio contable",
  website: "estudioscontable.com.ar",
  signals: {
    accessible: true,
    httpsOk: true,
    hasPhone: true,
    hasAddress: false,
    hasContactForm: true,
    hasLeadForm: false,
    hasOnlineBooking: false,
    hasSocialLinks: false,
    socialLinksFound: [],
    hasEcommerce: false,
    hasMetaPixel: false,
    hasAnalytics: true,
    hasGA4: false,
    h1Count: 1,
    hasSchema: false,
    hasSitemap: true,
    hasCanonical: true,
    hasOgTags: false,
    hasMetaDescription: true,
    estimatedPageWeightKb: 40,
    imageCount: 5,
    mainNavSections: ["INICIO", "SERVICIOS", "CONTACTO"],
  },
};

// ============================================================================
// EXPORT ALL
// ============================================================================

export const TEST_DATA_STAGE_A = [
  // Bodegas
  { name: "Bodega Premium", data: BODEGA_PREMIUM },
  { name: "Bodega de Exportación", data: BODEGA_EXPORTACION },
  { name: "Bodega Boutique", data: BODEGA_BOUTIQUE },
  { name: "Bodega Venta Directa", data: BODEGA_VENTA_DIRECTA },
  { name: "Bodega + Restaurante", data: BODEGA_RESTAURANTE },

  // Restaurantes
  { name: "Restaurante Fusión", data: RESTAURANTE_FUSION },
  { name: "Restaurante Casual", data: RESTAURANTE_CASUAL },
  { name: "Restaurante Delivery", data: RESTAURANTE_DELIVERY },
  { name: "Fine Dining", data: RESTAURANTE_FINE_DINING },
  { name: "Restaurante Popup", data: RESTAURANTE_POPUP },

  // Retail
  { name: "Tienda de Moda", data: RETAIL_MODA },
  { name: "Tienda Electrodomésticos", data: RETAIL_ELECTRODOMESTICOS },
  { name: "Librería Online", data: RETAIL_LIBROS },
  { name: "Tienda Artesanía", data: RETAIL_ARTESANIA },
  { name: "Retail Premium", data: RETAIL_PREMIUM },

  // Servicios
  { name: "Consultoría Empresarial", data: SERVICIO_CONSULTORIA },
  { name: "Agencia de Marketing", data: SERVICIO_AGENCIA_MARKETING },
  { name: "Estudio Jurídico", data: SERVICIO_ABOGACIA },
  { name: "Gym Premium", data: SERVICIO_FITNESS },
  { name: "Estudio Contable", data: SERVICIO_CONTABILIDAD },
];
