/**
 * TEST DATA: 4 Casos reales de auditoría forense
 */
export const CASA_VIGIL = {
    id: "casa-vigil-001",
    nombreEmpresa: "Casa Vigil",
    rubro: "Restaurante de alta cocina",
    website: "universovigil.com",
    signals: {
        title: "UNIVERSO VIGIL",
        accessible: true,
        httpsOk: true,
        hasPhone: false,
        hasAddress: false,
        hasContactForm: false,
        hasLeadForm: false,
        hasOnlineBooking: false,
        hasSocialLinks: true,
        socialLinksFound: [
            "instagram.com",
            "facebook.com",
            "twitter.com",
        ],
        hasEcommerce: true,
        hasMetaPixel: false,
        hasAnalytics: true,
        hasGA4: true,
        hasGTM: true,
        h1Count: 0,
        hasSchema: false,
        hasSitemap: false,
        hasCanonical: false,
        hasOgTags: false,
        hasMetaDescription: true,
        estimatedPageWeightKb: 10,
        imageCount: 2,
        mainNavSections: [
            "UNIVERSO VIGIL",
            "COMPRA ONLINE",
            "HACER UNA RESERVA",
        ],
    },
};
export const PULENTA_ESTATE = {
    id: "pulenta-estate-001",
    nombreEmpresa: "Pulenta Estate",
    rubro: "Bodega de vinos premium",
    website: "pulentaestate.com",
    signals: {
        title: "Pulenta Estate",
        accessible: true,
        httpsOk: true,
        hasPhone: true,
        hasAddress: true,
        hasContactForm: true,
        hasLeadForm: true,
        hasOnlineBooking: true,
        hasSocialLinks: true,
        socialLinksFound: [
            "instagram.com",
            "facebook.com",
        ],
        hasEcommerce: true,
        hasMetaPixel: true,
        hasAnalytics: true,
        hasGA4: true,
        hasGTM: true,
        h1Count: 1,
        hasSchema: true,
        hasSitemap: true,
        hasCanonical: true,
        hasOgTags: true,
        hasMetaDescription: true,
        estimatedPageWeightKb: 150,
        imageCount: 25,
        mainNavSections: [
            "INICIO",
            "TURISMO",
            "TIENDA",
            "CONTACTO",
            "BODEGA",
            "TOURS",
        ],
    },
};
export const BODEGAS_LOPEZ = {
    id: "bodegas-lopez-001",
    nombreEmpresa: "Bodegas López",
    rubro: "Bodega de exportación",
    website: "bodegaslopez.com.ar",
    signals: null, // REGLA 3: NO signals = NO analysis
};
export const NORTON = {
    id: "norton-001",
    nombreEmpresa: "Norton Bodega",
    rubro: "Bodega y tienda online",
    website: "norton.com.ar",
    signals: {
        title: "Norton | Bodega y Tienda",
        accessible: true,
        httpsOk: true,
        hasPhone: true,
        hasAddress: true,
        hasContactForm: true,
        hasLeadForm: false,
        hasOnlineBooking: false,
        hasSocialLinks: true,
        socialLinksFound: [
            "instagram.com",
            "facebook.com",
        ],
        hasEcommerce: true,
        hasMetaPixel: true,
        hasAnalytics: true,
        hasGA4: true,
        hasGTM: false,
        h1Count: 1,
        hasSchema: false,
        hasSitemap: true,
        hasCanonical: true,
        hasOgTags: true,
        hasMetaDescription: true,
        estimatedPageWeightKb: 90,
        imageCount: 12,
        mainNavSections: [
            "INICIO",
            "TIENDA",
            "BODEGA",
            "CONTACTO",
            "VINOS",
        ],
    },
};
export const TEST_CASES = [
    { name: "Casa Vigil", data: CASA_VIGIL },
    { name: "Pulenta Estate", data: PULENTA_ESTATE },
    { name: "Bodegas López", data: BODEGAS_LOPEZ },
    { name: "Norton", data: NORTON },
];
