export const ERP_ROUTES = {
  dashboard: '/erp/dashboard',
  prospects: '/erp/comercial/prospectos',
  campaigns: '/erp/comercial/campanas',
  followup: '/erp/comercial/seguimiento',
  pipeline: '/erp/comercial/pipeline',
  meetings: '/erp/comercial/reuniones',
  clients: '/erp/clientes',
  services: '/erp/delivery/servicios',
  projects: '/erp/proyectos',
  tasks: '/erp/tareas',
  lab: '/erp/laboratorio',
  billing: '/erp/facturacion',
  tickets: '/erp/tickets',
  reports: '/erp/reportes',
  hostingGuard: '/erp/hostingguard',
  inspyraCloud: '/erp/inspyra-cloud',
  inspyraMail: '/erp/inspyra-mail',
  emailMarketing: '/erp/email-marketing',
  team: '/erp/equipo',
  settings: '/erp/configuracion',
  socialIntegrations: '/erp/integraciones-sociales',
  mcp: '/erp/mcp',
} as const
