export const PLANS = [
  {
    name: 'Emprendedor Digital',
    price: 'Desde',
    badge: null,
    description: 'Para quienes necesitan presencia online rápida y efectiva.',
    features: [
      'Landing page o web simple',
      'Diseño responsive mobile-first',
      'Hosting básico o VPS inicial',
      'Certificado SSL',
      'Botón de WhatsApp',
      'Formulario de contacto',
      'SEO básico on-page',
      'Publicación online',
    ],
    cta: 'Consultar plan',
    highlight: false,
  },
  {
    name: 'Negocio Online',
    price: 'Desde',
    badge: 'Más elegido',
    description: 'Para comercios, profesionales y pymes que quieren vender online.',
    features: [
      'Web institucional completa',
      'Secciones de servicios y blog',
      'Catálogo de productos',
      'Hosting VPS administrado',
      'Correos corporativos',
      'Google Analytics + Search Console',
      'SEO inicial completo',
      'Soporte mensual incluido',
    ],
    cta: 'Quiero este plan',
    highlight: true,
  },
  {
    name: 'Empresa Digital',
    price: 'Desde',
    badge: null,
    description: 'Para empresas que necesitan estabilidad, escalabilidad y software propio.',
    features: [
      'Sitio corporativo completo',
      'Software o panel administrativo',
      'Infraestructura VPS o AWS',
      'Backups automáticos',
      'Seguridad avanzada',
      'Monitoreo y alertas',
      'SEO técnico profesional',
      'Soporte prioritario',
    ],
    cta: 'Solicitar propuesta',
    highlight: false,
  },
  {
    name: 'Crecimiento Mensual',
    price: 'Mensual',
    badge: null,
    description: 'Acompañamiento continuo para que tu negocio siempre esté actualizado y creciendo.',
    features: [
      'Mantenimiento web mensual',
      'Backups y seguridad',
      'SEO mensual continuo',
      'Gestión de redes sociales',
      'Mejoras y actualizaciones',
      'Reportes de rendimiento',
      'Soporte técnico incluido',
    ],
    cta: 'Quiero mantenimiento',
    highlight: false,
  },
]
