/**
 * E2E — Research Agent Flow
 *
 * The single most important test in the Inspyra test suite.
 * A Research Agent token (service account) must be able to use the MCP tools
 * to create a real prospect in PostgreSQL, generate an audit log, and have
 * its permissions enforced — all through the API, never touching the DB directly.
 *
 * Run with:
 *   npm run test:e2e
 *
 * Requirements:
 *   - PostgreSQL running on port 5433 (docker-compose up)
 *   - API .env configured correctly
 */

import request from 'supertest';
import { Test } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { AppModule } from '../../src/app.module';
import { PrismaService } from '../../src/database/prisma.service';
import { ResponseInterceptor } from '../../src/common/interceptors/response.interceptor';
import { AgentAuditInterceptor } from '../../src/common/interceptors/agent-audit.interceptor';
import { AllExceptionsFilter } from '../../src/common/filters/http-exception.filter';

// The RESEARCH_AGENT_TOKEN seeded in the DB.
// This token is in openclaw.json and was generated by the service accounts seed.
const RESEARCH_AGENT_TOKEN =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYS1yZXNlYXJjaCIsImFnZW50SWQiOiJyZXNlYXJjaC1hZ2VudCIsInRlbmFudElkIjoiNDgzZTE5YWYtNDZlMC00ODBlLWE0ZWEtNWU4NTEzMjE2ZWY5Iiwic2NvcGVzIjpbInByb3NwZWN0cy5yZWFkIiwicHJvc3BlY3RzLmNyZWF0ZSIsInByb3NwZWN0cy51cGRhdGUiLCJpbnRlbC5yZWFkIl0sInR5cGUiOiJzZXJ2aWNlIiwiaWF0IjoxNzgwNTQ4OTk5LCJleHAiOjE4MTIwODQ5OTl9.puMQ6mcy6m3nBx8o4xnbyFpa-0hDNBibSMG4vHxUb6U';

const TENANT_ID = '483e19af-46e0-480e-a4ea-5e8513216ef9';
const E2E_COMPANY_NAME = 'E2E-Research-Flow-Test';

describe('E2E — Research Agent → MCP → API → PostgreSQL', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let createdProspectId: string;

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = module.createNestApplication();
    app.setGlobalPrefix('api/v1');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true, transformOptions: { enableImplicitConversion: true } }));
    app.useGlobalFilters(new AllExceptionsFilter());
    prisma = module.get(PrismaService);
    app.useGlobalInterceptors(new ResponseInterceptor(), new AgentAuditInterceptor(prisma));
    await app.init();

    // Clean any leftover test data from previous runs
    await prisma.prospect.deleteMany({
      where: { tenantId: TENANT_ID, nombreEmpresa: E2E_COMPANY_NAME },
    });
  });

  afterAll(async () => {
    if (createdProspectId) {
      await prisma.prospect.deleteMany({
        where: { id: { in: [createdProspectId] } },
      });
      await prisma.auditLog.deleteMany({
        where: { tenantId: TENANT_ID, action: 'POST /api/v1/prospects', changes: { path: ['agentId'], equals: 'research' } },
      });
    }
    await app.close();
  });

  // ─── Step 1: Token validation ────────────────────────────────────────────────
  it('Step 1 — RESEARCH_AGENT_TOKEN is accepted by the API', async () => {
    const res = await request(app.getHttpServer())
      .get('/api/v1/prospects')
      .set('Authorization', `Bearer ${RESEARCH_AGENT_TOKEN}`)
      .expect(200);

    expect(res.body.success).toBe(true);
  });

  // ─── Step 2: Service Intelligence (analyze_problems tool) ────────────────────
  it('Step 2 — GET /service-intelligence/analyze returns recommendations', async () => {
    const res = await request(app.getHttpServer())
      .get('/api/v1/service-intelligence/analyze?problems=Sin SEO local,Web desactualizada')
      .set('Authorization', `Bearer ${RESEARCH_AGENT_TOKEN}`)
      .expect(200);

    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.data)).toBe(true);
    // Each result must have the required MCP contract shape
    if (res.body.data.length > 0) {
      expect(res.body.data[0]).toHaveProperty('problema');
      expect(res.body.data[0]).toHaveProperty('prioridad');
      expect(res.body.data[0]).toHaveProperty('serviciosRecomendados');
    }
  });

  // ─── Step 3: Create prospect (create_prospect MCP tool) ──────────────────────
  it('Step 3 — POST /prospects with service token creates prospect in PostgreSQL', async () => {
    const res = await request(app.getHttpServer())
      .post('/api/v1/prospects')
      .set('Authorization', `Bearer ${RESEARCH_AGENT_TOKEN}`)
      .set('X-Agent-Id', 'research')
      .send({
        nombreEmpresa: E2E_COMPANY_NAME,
        ciudad: 'Buenos Aires',
        pais: 'Argentina',
        rubro: 'Test',
        problemasEncontrados: ['Sin SEO local', 'Web desactualizada'],
        oportunidadDetectada: 'E2E automated validation test — Research Agent flow',
        detectadoPor: 'IA',
      })
      .expect(201);

    expect(res.body.success).toBe(true);
    expect(res.body.data.nombreEmpresa).toBe(E2E_COMPANY_NAME);
    expect(res.body.data.detectadoPor).toBe('IA');
    expect(res.body.data.estado).toBe('NUEVO');
    expect(res.body.data.tenantId).toBe(TENANT_ID);
    expect(res.body.data.creadoPorId).toBeNull();

    createdProspectId = res.body.data.id;
    expect(createdProspectId).toBeTruthy();
  });

  // ─── Step 4: Verify in PostgreSQL ────────────────────────────────────────────
  it('Step 4 — Prospect exists in PostgreSQL with correct data', async () => {
    const prospect = await prisma.prospect.findUnique({
      where: { id: createdProspectId },
    });

    expect(prospect).not.toBeNull();
    expect(prospect!.nombreEmpresa).toBe(E2E_COMPANY_NAME);
    expect(prospect!.tenantId).toBe(TENANT_ID);
    expect(prospect!.detectadoPor).toBe('IA');
    expect(prospect!.estado).toBe('NUEVO');
    expect(prospect!.problemasEncontrados).toContain('Sin SEO local');
  });

  // ─── Step 5: Audit log generated ─────────────────────────────────────────────
  it('Step 5 — Audit log was generated with X-Agent-Id: research', async () => {
    // setImmediate ensures the async audit write has completed
    await new Promise<void>((resolve) => setImmediate(resolve));

    const logs = await prisma.auditLog.findMany({
      where: {
        tenantId: TENANT_ID,
        action: 'POST /api/v1/prospects',
      },
      orderBy: { createdAt: 'desc' },
      take: 5,
    });

    const e2eLog = logs.find((l) => {
      const changes = l.changes as Record<string, unknown>;
      return changes?.agentId === 'research';
    });

    expect(e2eLog).toBeDefined();
    expect((e2eLog!.changes as Record<string, unknown>).source).toBe('openclaw');
  });

  // ─── Step 6: Score assignment (update_prospect MCP tool) ─────────────────────
  it('Step 6 — PATCH /prospects/:id assigns score (simulates MCP update_prospect)', async () => {
    const res = await request(app.getHttpServer())
      .patch(`/api/v1/prospects/${createdProspectId}`)
      .set('Authorization', `Bearer ${RESEARCH_AGENT_TOKEN}`)
      .set('X-Agent-Id', 'research')
      .send({
        score: 70,
        nivelOportunidad: 'ALTA',
        estado: 'INVESTIGADO',
      })
      .expect(200);

    expect(res.body.data.score).toBe(70);
    expect(res.body.data.nivelOportunidad).toBe('ALTA');
    expect(res.body.data.estado).toBe('INVESTIGADO');
  });

  // ─── Step 7: Final state in PostgreSQL ───────────────────────────────────────
  it('Step 7 — Final prospect state in PostgreSQL reflects all agent writes', async () => {
    const prospect = await prisma.prospect.findUnique({
      where: { id: createdProspectId },
    });

    expect(prospect!.score).toBe(70);
    expect(prospect!.nivelOportunidad).toBe('ALTA');
    expect(prospect!.estado).toBe('INVESTIGADO');
    expect(prospect!.detectadoPor).toBe('IA');
  });

  // ─── Step 8: RBAC — service account cannot delete ────────────────────────────
  it('Step 8 — RBAC: service account cannot DELETE prospect (403)', async () => {
    await request(app.getHttpServer())
      .delete(`/api/v1/prospects/${createdProspectId}`)
      .set('Authorization', `Bearer ${RESEARCH_AGENT_TOKEN}`)
      .expect(403);

    // Confirm prospect still exists — the 403 protected it
    const still = await prisma.prospect.findUnique({ where: { id: createdProspectId } });
    expect(still).not.toBeNull();
    expect(still!.deletedAt).toBeNull();
  });

  // ─── Step 9: Invalid transition blocked ──────────────────────────────────────
  it('Step 9 — Invalid state transition (INVESTIGADO → NUEVO) returns 400', async () => {
    await request(app.getHttpServer())
      .patch(`/api/v1/prospects/${createdProspectId}`)
      .set('Authorization', `Bearer ${RESEARCH_AGENT_TOKEN}`)
      .send({ estado: 'NUEVO' })
      .expect(400);
  });
});
